2020-10-28 22:03:28,505 INFO    MainThread:40949 [wandb_init.py:_log_setup():293] Logging user logs to wandb/run-20201028_220328-2qrbo6xt/logs/debug.log
2020-10-28 22:03:28,505 INFO    MainThread:40949 [wandb_init.py:_log_setup():294] Logging internal logs to wandb/run-20201028_220328-2qrbo6xt/logs/debug-internal.log
2020-10-28 22:03:28,505 INFO    MainThread:40949 [wandb_setup.py:_flush():69] setting env: {}
2020-10-28 22:03:28,505 INFO    MainThread:40949 [wandb_setup.py:_flush():69] setting user settings: {'email': 'eunbee.jang@mail.mcgill.ca'}
2020-10-28 22:03:28,505 INFO    MainThread:40949 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn,fork,forkserver
2020-10-28 22:03:29,604 INFO    MainThread:40949 [wandb_run.py:_console_start():1290] atexit reg
2020-10-28 22:03:29,606 INFO    MainThread:40949 [wandb_run.py:_redirect():1160] redirect: SettingsConsole.REDIRECT
2020-10-28 22:03:29,607 INFO    MainThread:40949 [wandb_run.py:_redirect():1163] Redirecting console.
2020-10-28 22:03:29,607 INFO    MainThread:40949 [redirect.py:install():196] install start
2020-10-28 22:03:29,607 INFO    MainThread:40949 [redirect.py:install():211] install stop
2020-10-28 22:03:29,607 INFO    MainThread:40949 [redirect.py:install():196] install start
2020-10-28 22:03:29,607 INFO    MainThread:40949 [redirect.py:install():211] install stop
2020-10-28 22:03:29,607 INFO    MainThread:40949 [wandb_run.py:_redirect():1207] Redirects installed.
2020-10-28 22:03:36,887 INFO    MainThread:40949 [wandb_run.py:_atexit_cleanup():1263] got exitcode: 1
2020-10-28 22:03:36,887 INFO    MainThread:40949 [wandb_run.py:_restore():1235] restore
2020-10-28 22:03:36,887 INFO    MainThread:40949 [redirect.py:uninstall():215] uninstall start
2020-10-28 22:03:36,888 INFO    MainThread:40949 [redirect.py:_stop():264] _stop: stdout
2020-10-28 22:03:36,888 INFO    MainThread:40949 [redirect.py:_stop():270] _stop closed: stdout
2020-10-28 22:03:36,888 INFO    stdout    :40949 [redirect.py:_pipe_relay():119] relay done saw last write: stdout
2020-10-28 22:03:36,888 INFO    stdout    :40949 [redirect.py:_pipe_relay():135] relay done done: stdout
2020-10-28 22:03:36,888 INFO    MainThread:40949 [redirect.py:_stop():276] _stop joined: stdout
2020-10-28 22:03:36,888 INFO    MainThread:40949 [redirect.py:_stop():278] _stop rd closed: stdout
2020-10-28 22:03:36,888 INFO    MainThread:40949 [redirect.py:uninstall():219] uninstall done
2020-10-28 22:03:36,888 INFO    MainThread:40949 [redirect.py:uninstall():215] uninstall start
2020-10-28 22:03:36,889 INFO    MainThread:40949 [redirect.py:_stop():264] _stop: stderr
2020-10-28 22:03:36,889 INFO    MainThread:40949 [redirect.py:_stop():270] _stop closed: stderr
2020-10-28 22:03:36,889 INFO    stderr    :40949 [redirect.py:_pipe_relay():119] relay done saw last write: stderr
2020-10-28 22:03:36,889 INFO    stderr    :40949 [redirect.py:_pipe_relay():135] relay done done: stderr
2020-10-28 22:03:36,889 INFO    MainThread:40949 [redirect.py:_stop():276] _stop joined: stderr
2020-10-28 22:03:36,889 INFO    MainThread:40949 [redirect.py:_stop():278] _stop rd closed: stderr
2020-10-28 22:03:36,889 INFO    MainThread:40949 [redirect.py:uninstall():219] uninstall done
2020-10-28 22:03:39,704 ERROR   MainThread:40949 [wandb_run.py:_atexit_cleanup():1281] Problem finishing run
Traceback (most recent call last):
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1271, in _atexit_cleanup
    self._on_finish()
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1395, in _on_finish
    self.history._flush()
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 49, in _flush
    self._callback(row=self._data, step=self._step)
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 640, in _history_callback
    self._backend.interface.publish_history(row, step)
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/site-packages/wandb/interface/interface.py", line 171, in publish_history
    item.value_json = json_dumps_safer_history(v)
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/site-packages/wandb/util.py", line 546, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/eunbeejang/miniconda3/envs/py38/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not numpy.int64
